### PR TITLE
Conf travis

### PR DESCRIPTION
**Pull request by pvilaca**
Travis CI configuration

### CODE REVIEW

**Comment by Ru13en** [comment]
Ainda não consegue fazer deploy... https://travis-ci.org/biotextmining/core/builds/595234332?utm_source=github_status&utm_medium=notification

**Comment by pvilaca** [comment]
> Ainda não consegue fazer deploy... https://travis-ci.org/biotextmining/core/builds/595234332?utm_source=github_status&utm_medium=notification

I know... =( It is almost there...

**Comment by Ru13en** [comment]
Can i merge or will you make more changes?

**Comment by pvilaca** [comment]
> Can i merge or will you make more changes?

Sorry for @Ru13en . Just saw your post now. It is closed ;)
CI rules!!! ;)

**Pull request merged**
